PUSHUPS = "PUSHUPS"
PULLUPS = "PULLUPS"
FRONT = "_FRONT"
RIGHT = "_RIGHT"
LEFT = "_LEFT"
MULTIPLE = "_MULTIPLE"
BAD = "_BAD"

ASCENDING = "ASCENDING"
DESCENDING = "DESCENDING"

PUSHUPS_LEFT = PUSHUPS + LEFT
PUSHUPS_RIGHT = PUSHUPS + RIGHT
PUSHUPS_FRONT = PUSHUPS + FRONT

AUTO = "AUTO"
MANUAL = "MANUAL"
TRUE = "TRUE"
FALSE = "FALSE"

OK = "OK"
INCOMPLETE = "INCOMPLETE"
WRONG = "WRONG"
